{% set name = "opentelemetry-instrumentation-starlette" %}
{% set version = "0.46b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_starlette-{{ version }}.tar.gz
  sha256: c13ad133a386aa6733832949121d711f420832a79409cab8e663e3c5c2ac4a38

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-asgi ==0.46b0
    - opentelemetry-instrumentation ==0.46b0
    - opentelemetry-semantic-conventions ==0.46b0
    - opentelemetry-util-http ==0.46b0
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - starlette ~=0.13.0
test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-starlette
  summary: OpenTelemetry Starlette Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
