{% set name = "opentelemetry-instrumentation-starlette" %}
{% set version = "0.55b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_starlette-{{ version }}.tar.gz
  sha256: c6592bb6ddf98d12a3165d0e9bd16652f438930bfe01b99e9a8009d534f2bc62

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-asgi ==0.55b0
    - opentelemetry-instrumentation ==0.55b0
    - opentelemetry-semantic-conventions ==0.55b0
    - opentelemetry-util-http ==0.55b0
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - requests ~=2.23
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-starlette 
    # - httpx ~=0.22
    # - starlette ~=0.13.0
    # - starlette ~=0.13.0
    # - starlette ~=0.13.0
    # - starlette ~=0.13.0
    # - starlette ~=0.13.0
    # - starlette ~=0.13.0
    # - starlette ~=0.13.0
    # - starlette ~=0.13.0
    # - starlette <0.15,>=0.13
    # - starlette <0.15,>=0.13
    # - starlette <0.15,>=0.13
    # - starlette <0.15,>=0.13
    # - starlette <0.15,>=0.13
    # - starlette <0.15,>=0.13
    # - starlette >=0.13
test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-starlette
  summary: OpenTelemetry Starlette Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
